type Player = {
  playerID: number;
  teamCode: string;
  name: string;
  fname: string;
  nickname?: string;
  position: string;
  goals: number;
  assists: number;
  isCaptain?: boolean;
};

export const players: Player[] = [
  /**
   * Chemical
   */
  {
    playerID: 1021,
    teamCode: "CHE",
    name: "Fasil",
    fname: "",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1022,
    teamCode: "CHE",
    name: "Haile",
    fname: "",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1023,
    teamCode: "CHE",
    name: "Sibhat",
    fname: "",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1024,
    teamCode: "CHE",
    name: "Temesgen",
    fname: "Abay",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1025,
    teamCode: "CHE",
    name: "Abdusemed",
    fname: "Seid",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1026,
    teamCode: "CHE",
    name: "Yemesgen",
    fname: "Fantahun",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1027,
    teamCode: "CHE",
    name: "Yonatan",
    fname: "Gashaw",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1028,
    teamCode: "CHE",
    name: "Abel",
    fname: "",
    position: "ST",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1029,
    teamCode: "CHE",
    name: "Amanuel",
    fname: "",
    position: "ST",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10210,
    teamCode: "CHE",
    name: "Ewnetu",
    fname: "",
    position: "ST",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10211,
    teamCode: "CHE",
    name: "Haftamu",
    fname: "",
    position: "ST",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10212,
    teamCode: "CHE",
    name: "Olan",
    fname: "",
    position: "ST",
    goals: 0,
    assists: 0,
  },

  /**
   * Civil 1
   */
  {
    playerID: 1031,
    teamCode: "CV1",
    name: "Henock",
    fname: "Meseret",
    position: "GK",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1032,
    teamCode: "CV1",
    name: "Abdulaziz",
    fname: "Ali",
    position: "GK",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1033,
    teamCode: "CV1",
    name: "Biruk",
    fname: "Ayele",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1034,
    teamCode: "CV1",
    name: "Sewnet",
    fname: "Ayele",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1035,
    teamCode: "CV1",
    name: "Yonas",
    fname: "Esubalew",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1036,
    teamCode: "CV1",
    name: "Yonas",
    fname: "Mekdes",
    position: "DF",
    goals: 0,
    assists: 0,
    isCaptain: true,
  },
  {
    playerID: 1037,
    teamCode: "CV1",
    name: "Kibrom",
    fname: "Atnafu",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1038,
    teamCode: "CV1",
    name: "Natnael",
    fname: "G/mariam",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1039,
    teamCode: "CV1",
    name: "Natnael",
    fname: "Molla",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10310,
    teamCode: "CV1",
    name: "Elias",
    fname: "Yemane",
    position: "ST",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10311,
    teamCode: "CV1",
    name: "Kaleab",
    fname: "Mulat",
    position: "ST",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10312,
    teamCode: "CV1",
    name: "Kaleab",
    fname: "Wendwesen",
    position: "ST",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10313,
    teamCode: "CV1",
    name: "Robel",
    fname: "Yohannes",
    position: "ST",
    goals: 0,
    assists: 0,
  },

  /**
   * Civil 2
   */
  {
    playerID: 1041,
    teamCode: "CV2",
    name: "Abenezer",
    fname: "Muluneh",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1042,
    teamCode: "CV2",
    name: "Amir",
    fname: "Kedir",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1043,
    teamCode: "CV2",
    name: "Nebiyu",
    fname: "Samuel",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1044,
    teamCode: "CV2",
    name: "Tewodros",
    fname: "Abebe",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1045,
    teamCode: "CV2",
    name: "Tsigab",
    fname: "Kube",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1046,
    teamCode: "CV2",
    name: "Dagimawi",
    fname: "Mekonen",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1047,
    teamCode: "CV2",
    name: "Samuel",
    fname: "Bizuneh",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1048,
    teamCode: "CV2",
    name: "Yeabsira",
    fname: "Tibebu",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1049,
    teamCode: "CV2",
    name: "Yohannes",
    fname: "Debebe",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10410,
    teamCode: "CV2",
    name: "Fkire",
    fname: "Abadi",
    position: "ST",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10411,
    teamCode: "CV2",
    name: "Hachalu",
    fname: "Hailu",
    position: "ST",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10412,
    teamCode: "CV2",
    name: "Robel",
    fname: "Argaw",
    position: "ST",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10413,
    teamCode: "CV2",
    name: "Yeshitla",
    fname: "G/michael",
    position: "ST",
    goals: 0,
    assists: 0,
  },

  /**
   * Electrical A
   */
  {
    playerID: 1051,
    teamCode: "ELA",
    name: "Alemu",
    fname: "Molla",
    position: "GK",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1052,
    teamCode: "ELA",
    name: "Dagmawi",
    fname: "G/weld",
    position: "GK",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1053,
    teamCode: "ELA",
    name: "Beka",
    fname: "Biru",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1054,
    teamCode: "ELA",
    name: "Firaol",
    fname: "",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1055,
    teamCode: "ELA",
    name: "Gemechu",
    fname: "Birhanu",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1056,
    teamCode: "ELA",
    name: "Natnael",
    fname: "Fitsum",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1057,
    teamCode: "ELA",
    name: "Ababu",
    fname: "Alemu",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1058,
    teamCode: "ELA",
    name: "Abebaw",
    fname: "Assefa",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1059,
    teamCode: "ELA",
    name: "Bereket",
    fname: "Barma",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10510,
    teamCode: "ELA",
    name: "Mohammed",
    fname: "Hussein",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10511,
    teamCode: "ELA",
    name: "Nahom",
    fname: "Sileshi",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10512,
    teamCode: "ELA",
    name: "Yeshiwas",
    fname: "Tikmu",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10513,
    teamCode: "ELA",
    name: "Abraham",
    fname: "Mulat",
    position: "ST",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10514,
    teamCode: "ELA",
    name: "Chala",
    fname: "Tadesse",
    position: "ST",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10515,
    teamCode: "ELA",
    name: "Henok",
    fname: "Hailu",
    position: "ST",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10516,
    teamCode: "ELA",
    name: "Natnael",
    fname: "Mersha",
    position: "ST",
    goals: 0,
    assists: 0,
  },

  /**
   * Electrical B
   */
  {
    playerID: 1061,
    teamCode: "ELB",
    name: "Sisay",
    fname: "Bekele",
    position: "GK",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1062,
    teamCode: "ELB",
    name: "Fitsum",
    fname: "Getachew",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1063,
    teamCode: "ELB",
    name: "Girmachew",
    fname: "Mengistu",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1064,
    teamCode: "ELB",
    name: "Kassa",
    fname: "Birhanu",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1065,
    teamCode: "ELB",
    name: "Mulugeta",
    fname: "Mekuanint",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1066,
    teamCode: "ELB",
    name: "Nehemiah",
    fname: "Yishak",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1067,
    teamCode: "ELB",
    name: "Bereket",
    fname: "Nigussie",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1068,
    teamCode: "ELB",
    name: "Bultum",
    fname: "Guluma",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1069,
    teamCode: "ELB",
    name: "Mohammed",
    fname: "",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10610,
    teamCode: "ELB",
    name: "Nigatu",
    fname: "Paulos",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10611,
    teamCode: "ELB",
    name: "Samuel",
    fname: "Negalign",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10612,
    teamCode: "ELB",
    name: "Biniyam",
    fname: "Dagne",
    position: "ST",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10613,
    teamCode: "ELB",
    name: "Birhanu",
    fname: "Adama",
    position: "ST",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10614,
    teamCode: "ELB",
    name: "Kaleb",
    fname: "Tesfay",
    position: "ST",
    goals: 0,
    assists: 0,
  },

  /**
   * IT
   */
  {
    playerID: 1071,
    teamCode: "ITE",
    name: "Michael",
    fname: "Alemayehu",
    position: "GK",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1072,
    teamCode: "ITE",
    name: "Barok",
    fname: "Dagim",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1073,
    teamCode: "ITE",
    name: "Dawit",
    fname: "Bezabih",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1074,
    teamCode: "ITE",
    name: "Ermias",
    fname: "Asmare",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1075,
    teamCode: "ITE",
    name: "Haben",
    fname: "Tesfaye",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1076,
    teamCode: "ITE",
    name: "Yeabsira",
    fname: "Mezgebu",
    nickname: "Yabs",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1077,
    teamCode: "ITE",
    name: "Zekarias",
    fname: "Alemu",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1078,
    teamCode: "ITE",
    name: "Ermias",
    fname: "Mulugeta",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1079,
    teamCode: "ITE",
    name: "Kevin",
    fname: "Shitaye",
    position: "MD",
    goals: 0,
    assists: 0,
    isCaptain: true,
  },
  {
    playerID: 10710,
    teamCode: "ITE",
    name: "Tekletsadik",
    fname: "Abebayehu",
    nickname: "Tekle",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10711,
    teamCode: "ITE",
    name: "Yonathan",
    fname: "Awoke",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10712,
    teamCode: "ITE",
    name: "Beken",
    fname: "Adugna",
    position: "ST",
    goals: 0,
    assists: 0,
  },

  /**
   * Software 1
   */
  {
    playerID: 1091,
    teamCode: "SF1",
    name: "Liben",
    fname: "Hailu",
    position: "GK",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1092,
    teamCode: "SF1",
    name: "Alefew",
    fname: "Yimer",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1093,
    teamCode: "SF1",
    name: "Derbachew",
    fname: "",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1094,
    teamCode: "SF1",
    name: "Ebsa",
    fname: "",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1095,
    teamCode: "SF1",
    name: "Solomon",
    fname: "Ermias",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1096,
    teamCode: "SF1",
    name: "Temesgen",
    fname: "Talo",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1097,
    teamCode: "SF1",
    name: "Betsegaw",
    fname: "",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1098,
    teamCode: "SF1",
    name: "Daniel",
    fname: "",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1099,
    teamCode: "SF1",
    name: "Natnael",
    fname: "Awel",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10910,
    teamCode: "SF1",
    name: "Suraphel",
    fname: "Kindu",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10911,
    teamCode: "SF1",
    name: "Nahom",
    fname: "Zerihun",
    position: "ST",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 10912,
    teamCode: "SF1",
    name: "Yididya",
    fname: "",
    position: "ST",
    goals: 0,
    assists: 0,
  },

  /**
   * Software 2
   */
  {
    playerID: 1101,
    teamCode: "SF2",
    name: "Dagnachew",
    fname: "",
    position: "GK",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1102,
    teamCode: "SF2",
    name: "Asegd",
    fname: "",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1103,
    teamCode: "SF2",
    name: "Hawitu",
    fname: "",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1104,
    teamCode: "SF2",
    name: "Zerihun",
    fname: "",
    position: "DF",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1105,
    teamCode: "SF2",
    name: "Dawit",
    fname: "Teshager",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1106,
    teamCode: "SF2",
    name: "Fantahun",
    fname: "Fekadu",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1107,
    teamCode: "SF2",
    name: "Natnael",
    fname: "Bahiru",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1108,
    teamCode: "SF2",
    name: "Natnael",
    fname: "Berhanu",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 1109,
    teamCode: "SF2",
    name: "Robel",
    fname: "Azmeraw",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 11010,
    teamCode: "SF2",
    name: "Yohannes",
    fname: "",
    position: "MD",
    goals: 0,
    assists: 0,
  },
  {
    playerID: 11011,
    teamCode: "SF2",
    name: "Emnet",
    fname: "Yohannes",
    position: "ST",
    goals: 0,
    assists: 0,
  },
];
