type Team = {
  teamID: number;
  teamName: string;
  teamCode: string;
  previousRank: number; // *optional
  played: number;
  points: number;
  wins: number;
  draws: number;
  losses: number;
  goalsFor: number;
  goalsAgainst: number;
  goalDifference: number;
  lastFive: string;
  cleansheets: number;
};

export const teams: Team[] = [
  {
    teamID: 101,
    teamName: "Biomed",
    teamCode: "BIO",
    previousRank: 0,
    played: 0,
    points: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    lastFive: "",
    cleansheets: 0,
  },
  {
    teamID: 102,
    teamName: "Chemical",
    teamCode: "CHE",
    previousRank: 0,
    played: 0,
    points: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    lastFive: "",
    cleansheets: 0,
  },
  {
    teamID: 103,
    teamName: "Civil 1",
    teamCode: "CV1",
    previousRank: 0,
    played: 0,
    points: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    lastFive: "",
    cleansheets: 0,
  },
  {
    teamID: 104,
    teamName: "Civil 2",
    teamCode: "CV2",
    previousRank: 0,
    played: 0,
    points: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    lastFive: "",
    cleansheets: 0,
  },
  {
    teamID: 105,
    teamName: "Electrical A",
    teamCode: "ELA",
    previousRank: 0,
    played: 0,
    points: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    lastFive: "",
    cleansheets: 0,
  },
  {
    teamID: 106,
    teamName: "Electrical B",
    teamCode: "ELB",
    previousRank: 0,
    played: 0,
    points: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    lastFive: "",
    cleansheets: 0,
  },
  {
    teamID: 107,
    teamName: "IT",
    teamCode: "ITE",
    previousRank: 0,
    played: 0,
    points: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    lastFive: "",
    cleansheets: 0,
  },
  {
    teamID: 108,
    teamName: "Mechanical",
    teamCode: "MEC",
    previousRank: 0,
    played: 0,
    points: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    lastFive: "",
    cleansheets: 0,
  },
  {
    teamID: 109,
    teamName: "Software 1",
    teamCode: "SF1",
    previousRank: 0,
    played: 0,
    points: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    lastFive: "",
    cleansheets: 0,
  },
  {
    teamID: 110,
    teamName: "Software 2",
    teamCode: "SF2",
    previousRank: 0,
    played: 0,
    points: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    lastFive: "",
    cleansheets: 0,
  },
];
