type Team = {
  teamID: Number;
  teamName: String;
  teamCode: String;
  played: Number;
  points: Number;
  wins: Number;
  draws: Number;
  losses: Number;
  goalsFor: Number;
  goalsAgainst: Number;
  goalDifference: Number;
  lastFive: String;
  cleansheets: Number;
};

export const teams: Team[] = [
  {
    teamID: 101,
    teamName: "Biomed",
    teamCode: "BIO",
    played: 0,
    points: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    lastFive: "",
    cleansheets: 0,
  },
  {
    teamID: 102,
    teamName: "Civil 1",
    teamCode: "CV1",
    played: 0,
    points: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    lastFive: "",
    cleansheets: 0,
  },
  {
    teamID: 103,
    teamName: "Civil 2",
    teamCode: "CV2",
    played: 0,
    points: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    lastFive: "",
    cleansheets: 0,
  },
  {
    teamID: 104,
    teamName: "Chemical",
    teamCode: "CHE",
    played: 0,
    points: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    lastFive: "",
    cleansheets: 0,
  },
  {
    teamID: 105,
    teamName: "Electrical 1",
    teamCode: "EL1",
    played: 0,
    points: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    lastFive: "",
    cleansheets: 0,
  },
  {
    teamID: 106,
    teamName: "Electrical 2",
    teamCode: "EL2",
    played: 0,
    points: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    lastFive: "",
    cleansheets: 0,
  },
  {
    teamID: 107,
    teamName: "IT",
    teamCode: "ITE",
    played: 0,
    points: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    lastFive: "",
    cleansheets: 0,
  },
  {
    teamID: 108,
    teamName: "Mechanical",
    teamCode: "MEC",
    played: 0,
    points: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    lastFive: "",
    cleansheets: 0,
  },
  {
    teamID: 109,
    teamName: "Software 1",
    teamCode: "SF1",
    played: 0,
    points: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    lastFive: "",
    cleansheets: 0,
  },
  {
    teamID: 110,
    teamName: "Software 2",
    teamCode: "SF2",
    played: 0,
    points: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    lastFive: "",
    cleansheets: 0,
  },
];
